apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-win
  namespace: test-win
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-storage
