apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-win
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /6b7f0a2c5e3047fda5331c472feff035
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: agentpool
              operator: In
              values:
                - win
