apiVersion: v1
kind: Namespace
metadata:
  annotations:
    linkerd.io/inject: disabled
    scheduler.alpha.kubernetes.io/defaultTolerations: '[
      {"operator": "Equal", "effect": "NoSchedule", "key": "dedicated", "value": "win"},
      {"operator": "Equal", "effect": "NoSchedule", "key": "kubernetes.azure.com/scalesetpriority", "value": "spot"}
      ]'
    scheduler.alpha.kubernetes.io/node-selector: agentpool=win
  labels:
    kubernetes.io/metadata.name: test
  name: test-win
